// Generates content/blocks-data.ts so block source/file-tree content is
// bundled into the JS build instead of read from disk at request time.
// Cloudflare Workers cannot do `fs.readFileSync(process.cwd() + '...')` for
// repo files at runtime, so we inline the content here.

import fs from 'node:fs';
import path from 'node:path';

type FileItem = {
  type: 'file';
  name: string;
  path: string;
  content: string;
};

type FolderItem = {
  type: 'folder';
  name: string;
  path: string;
  children: FileTreeItem[];
};

type FileTreeItem = FileItem | FolderItem;

const projectRoot = process.cwd();
const componentsDir = path.join(projectRoot, 'content', 'components');
const outputPath = path.join(projectRoot, 'content', 'blocks-data.ts');

function wrapTsx(content: string): string {
  return `\`\`\`\`tsx\n${content.trim()}\n\`\`\`\``;
}

function readTree(dir: string, base: string = dir): FileTreeItem[] {
  const items: FileTreeItem[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) {
      continue;
    }
    const entryPath = path.join(dir, entry.name);
    const relativePath = path.relative(base, entryPath);
    if (entry.isDirectory()) {
      items.push({
        type: 'folder',
        name: entry.name,
        path: relativePath,
        children: readTree(entryPath, base),
      });
    } else if (entry.isFile()) {
      items.push({
        type: 'file',
        name: entry.name,
        path: relativePath,
        content: fs.readFileSync(entryPath, 'utf-8'),
      });
    }
  }
  items.sort((a, b) => {
    if (a.type === 'folder' && b.type === 'file') {
      return -1;
    }
    if (a.type === 'file' && b.type === 'folder') {
      return 1;
    }
    return a.name.localeCompare(b.name);
  });
  return items;
}

const blocksSource: Record<string, string> = {};
const blocksTree: Record<string, FileTreeItem[]> = {};

for (const categoryEntry of fs.readdirSync(componentsDir, {
  withFileTypes: true,
})) {
  if (!categoryEntry.isDirectory()) {
    continue;
  }
  const categoryDir = path.join(componentsDir, categoryEntry.name);

  for (const entry of fs.readdirSync(categoryDir, { withFileTypes: true })) {
    if (entry.name === 'index.ts') {
      continue;
    }
    if (entry.name.startsWith('.')) {
      continue;
    }

    const entryPath = path.join(categoryDir, entry.name);

    if (entry.isFile() && path.extname(entry.name) === '.tsx') {
      const blockId = path.basename(entry.name, '.tsx');
      const content = fs.readFileSync(entryPath, 'utf-8');
      blocksSource[blockId] = wrapTsx(content);
    } else if (entry.isDirectory()) {
      const blockId = entry.name;
      blocksTree[blockId] = readTree(entryPath);
    }
  }
}

const sortedSourceIds = Object.keys(blocksSource).sort();
const sortedTreeIds = Object.keys(blocksTree).sort();

const sourceLines = sortedSourceIds
  .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(blocksSource[id])},`)
  .join('\n');

const treeLines = sortedTreeIds
  .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(blocksTree[id])},`)
  .join('\n');

const output = `// Generated by scripts/generate-blocks-data.ts. Do not edit manually.
// Run \`bun run generate:blocks-data\` to regenerate.

import type { FileTreeItem } from '@/lib/blocks';

export const blocksSource: Record<string, string> = {
${sourceLines}
};

export const blocksTree: Record<string, FileTreeItem[]> = {
${treeLines}
};
`;

fs.writeFileSync(outputPath, output);

process.stdout.write(
  `Wrote ${outputPath}: ${sortedSourceIds.length} file blocks, ${sortedTreeIds.length} directory blocks\n`
);
